<?php
declare(strict_types=1);

namespace core;

class ApiDoc
{
    private array $docs = [];

    public function generate(): array
    {
        $this->docs = [];
        $this->scanControllers();
        $this->scanRoutes();
        return $this->docs;
    }

    public function toMarkdown(): string
    {
        $docs = $this->generate();
        $md = "# API Documentation\n\n";
        $md .= "Generated by LightPHP Framework\n\n";

        foreach ($docs as $group => $endpoints) {
            $md .= "## {$group}\n\n";
            $md .= "| Method | Endpoint | Description |\n";
            $md .= "|--------|----------|-------------|\n";

            foreach ($endpoints as $endpoint) {
                $method = $endpoint['method'] ?? 'GET';
                $uri = $endpoint['uri'] ?? '/';
                $description = $endpoint['description'] ?? '-';
                $md .= "| {$method} | `{$uri}` | {$description} |\n";
            }
            $md .= "\n";
        }

        return $md;
    }

    public function toJson(): string
    {
        $encoded = json_encode($this->generate(), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
        return $encoded !== false ? $encoded : '[]';
    }

    private function scanControllers(): void
    {
        $controllerPath = APP_PATH . 'controller/';
        if (!is_dir($controllerPath)) {
            return;
        }

        $files = glob($controllerPath . '*.php');
        if ($files === false) {
            return;
        }

        foreach ($files as $file) {
            $this->parseController($file);
        }
    }

    private function parseController(string $file): void
    {
        $content = file_get_contents($file);
        if ($content === false) {
            return;
        }

        $className = $this->extractClassName($content);
        if (!$className) {
            return;
        }

        $fullClass = $this->extractNamespace($content);
        if ($fullClass) {
            $fullClass .= '\\' . $className;
        } else {
            $fullClass = $className;
        }

        if (!class_exists($fullClass)) {
            require_once $file;
        }

        if (!class_exists($fullClass)) {
            return;
        }

        $reflection = new \ReflectionClass($fullClass);
        $methods = $reflection->getMethods(\ReflectionMethod::IS_PUBLIC);

        foreach ($methods as $method) {
            $methodName = $method->getName();
            if ($method->getDeclaringClass()->getName() !== $fullClass) {
                continue;
            }

            if (!in_array($methodName, ['__construct', 'index', 'show', 'store', 'update', 'destroy'], true)) {
                continue;
            }

            $docComment = $method->getDocComment();
            $description = $this->extractDescription($docComment ?: '');
            $params = $this->extractParams($docComment ?: '');

            $this->docs[$className][] = [
                'method' => $this->guessHttpMethod($methodName),
                'uri' => $this->guessUri($className, $methodName),
                'description' => $description,
                'parameters' => $params,
                'controller' => $className,
                'action' => $methodName,
            ];
        }
    }

    private function scanRoutes(): void
    {
        $routeFiles = glob(APP_PATH . 'route/*.php');
        if ($routeFiles === false) {
            return;
        }

        foreach ($routeFiles as $routeFile) {
            if (!file_exists($routeFile)) {
                continue;
            }

            $content = file_get_contents($routeFile);
            if ($content === false) {
                continue;
            }

            preg_match_all(
                '/\$router->(get|post|put|delete|patch|any)\s*\(\s*[\'"]([^\'"]+)[\'"]\s*,/',
                $content,
                $matches,
                PREG_SET_ORDER
            );

            if (empty($matches)) {
                continue;
            }

            foreach ($matches as $match) {
                $this->docs['Routes'][] = [
                    'method' => strtoupper($match[1]),
                    'uri' => $match[2],
                    'description' => '',
                    'parameters' => [],
                    'controller' => '',
                    'action' => '',
                ];
            }
        }
    }

    private function extractClassName(string $content): ?string
    {
        if (preg_match('/class\s+(\w+)/', $content, $matches)) {
            return $matches[1];
        }
        return null;
    }

    private function extractNamespace(string $content): ?string
    {
        if (preg_match('/namespace\s+([^;]+);/', $content, $matches)) {
            return trim($matches[1]);
        }
        return null;
    }

    private function extractDescription(string $docComment): string
    {
        if ($docComment === '') {
            return '';
        }

        if (preg_match('/\*\s*([^@\n]+)/', $docComment, $matches)) {
            return trim($matches[1]);
        }

        return '';
    }

    private function extractParams(string $docComment): array
    {
        $params = [];
        if ($docComment === '') {
            return $params;
        }

        preg_match_all(
            '/@param\s+(\w+)\s+\$(\w+)\s*(.*)/',
            $docComment,
            $matches,
            PREG_SET_ORDER
        );

        foreach ($matches as $match) {
            $params[] = [
                'type' => $match[1],
                'name' => $match[2],
                'description' => trim($match[3]),
            ];
        }

        return $params;
    }

    private function guessHttpMethod(string $methodName): string
    {
        return match ($methodName) {
            'index', 'show' => 'GET',
            'store' => 'POST',
            'update' => 'PUT',
            'destroy' => 'DELETE',
            default => 'GET',
        };
    }

    private function guessUri(string $className, string $methodName): string
    {
        $className = str_replace('Controller', '', $className);
        $base = '/' . strtolower((string) preg_replace('/([a-z])([A-Z])/', '$1-$2', $className));

        if ($methodName === 'index') {
            return $base;
        }

        if (in_array($methodName, ['show', 'update', 'destroy'], true)) {
            return $base . '/{id}';
        }

        return $base . '/' . strtolower($methodName);
    }
}